application: connexus-vbill-sruth
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /css
  static_dir: css

- url: /trendingShort
  script: connexus.application
  login: admin

- url: /trendingHourly
  script: connexus.application
  login: admin

- url: /trendingDaily
  script: connexus.application
  login: admin

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /ui
  static_dir: ui

- url: /(favicon\.ico|robots\.txt)
  static_files: static/\1
  upload: static/(.*)
  expiration: '1d'

- url: /.*
  script: connexus.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
